### ISSUE TITLE
Volume prediction by R3PG

### ISSUE THREAD

**Issue by Theo025** [trotsiuk/r3PG#41]
I tried using R3PG to simulate one of my study sites and i found that the DBH and Height predictions were doing fine but the volume predictions were quite funny. The volumes were over predicted (DBH = 1.97cm and Height = 1.59m was yielding volume of 344.8 m3ha-1). I checked the function used for volume calculation and i found it was quite different from the 3PGpjs version. I went further to calculate the volume manually using this equation from the R3PG code and i got the same funny volume.

**Comment by trotsiuk** [comment]
Dear @Theo025, thank you for the  notification. 
There are few options to calculate stand volume, as you probably have seen over the fortran script. Furthermore, different setting might change that calculation. 
To answer your question, please provide a reproducible example of the code (including the input data and parameters).

The test example from the package provide a reasonable volume estimation:

```
library(r3PG)
library(dplyr)
library(ggplot2)


out_3PG <- run_3PG(
  site        = d_site, 
  species     = d_species, 
  climate     = d_climate, 
  thinning    = d_thinning,
  parameters  = d_parameters, 
  size_dist   = d_sizeDist,
  settings    = list(light_model = 2, transp_model = 2, phys_model = 2, 
                     height_model = 1, correct_bias = 0, calculate_d13c = 0),
  check_input = TRUE, df_out = TRUE)


sel_var <- c('biom_stem', 'biom_foliage', 'biom_root', 'volume')

out_3PG %>%
  filter( variable %in% sel_var ) %>%
  ggplot( aes(date, value, color = species) ) +
  geom_line() +
  facet_wrap(~variable, scales = 'free') +
  theme_classic()
```

![image](https://user-images.githubusercontent.com/15097779/92503615-d1fb0700-f201-11ea-87be-d07772249947.png)

**Comment by Theo025** [comment]
Dear @trotsiuk,

Thank you for your response. Below is the R code and I have also attached the input data

`library(r3PG)`
`library(readxl)`
`F_site <- read_excel("Inputdata.xlsx", sheet = 'site')`
`F_species <- read_excel("Inputdata.xlsx", sheet = 'species')`
`F_climate <- read_excel("Inputdata.xlsx", sheet = 'climate')`
`F_parameters <- read_excel("Inputdata.xlsx", sheet = 'parameters')`

`prepare_climate( climate = F_climate, from = '2010-08', to = '2018-08')`
`prepare_parameters( parameters = F_parameters,
                    sp_names = 'Eucalyptus grandis x urophylla')`
`prepare_input( site = F_site, species = F_species, climate = F_climate, parameters = F_parameters,
               thinning = NULL, size_dist = NULL)`

`sm <- run_3PG(`
  `site        = F_site,`
  `species     = F_species,`
  `climate     = F_climate,`
 ` thinning    = NULL,`
  `parameters  = F_parameters,`
  `size_dist   = NULL,`
  `settings    = list(light_model = 1, transp_model = 1, phys_model = 1,`
                     `height_model = 1, correct_bias = 0, calculate_d13c = 0),`
  `check_input = TRUE, df_out = TRUE)`


[Inputdata.xlsx](https://github.com/trotsiuk/r3PG/files/5190049/Inputdata.xlsx)

**Comment by DavidForrester** [comment]
Dear Theo025

Thanks for the question. The volume is over-predicted because of the aV and nVB parameters you provided. The volume for 3-PG is predicted in cubic m (per tree) and then multiplied by the number of trees. So the volume predicted using your parameters must be cubic m. The equation form can be found on p. 66 (Equation A66) of the following document. 

The volume parameters are not used to calculate anything else, and volume is not used in any other calculations, so no other outputs should be incorrect. Please let me know if I have misunderstood something.

[3PGmix_UserManual.pdf](https://github.com/trotsiuk/r3PG/files/5190446/3PGmix_UserManual.pdf)

**Comment by trotsiuk** [comment]
Dear @DavidForrester and @Theo025 

According to the [VBA version available from website](https://sites.google.com/site/davidforresterssite/home/projects/3PGmix) the equation used in VBA is:

```
StandVol(speciescounter2) = aV(speciescounter2) * avDBH(speciescounter2) ^ nVB(speciescounter2) * Height(speciescounter2) ^ nVH(speciescounter2) * (avDBH(speciescounter2) * avDBH(speciescounter2) * Height(speciescounter2)) ^ nVBH(speciescounter2) * StemNo(speciescounter2) _
```

To my understanding it is identical to the [Fortran implementation](https://github.com/trotsiuk/r3PG/blob/c828c4d79b144483957555fb0caffd303266dc8d/pkg/src/md_3PG.f95#L210).

```
volume(:) = aV(:) * dbh(:) ** nVB(:) * height(:) ** nVH(:) * (dbh(:) * dbh(:) * height(:)) ** nVBH(:) * stems_n(:)
```
Please correct me if I'm wrong

**Comment by DavidForrester** [comment]
Good point. In the 3PGpjs script, the volume is calculated as:
    Then StandVol = aV * avDBH ^ nVB * StemNo ^ nVN _
    Else StandVol = WS * (1 - fracBB) / Density

so the first part of the equation is the same as in r3PG, but the r3PG also gives the option of using height. The difference only occurs when height parameters (nVH or nVBH) are also provided. These were added because volume is often also calculated using height or DBH*DBH*height, so several users wanted this addition to improve the accuracy of the volume. Another change relating to stand volume calculations was that the mean annual volume increment (MAI) of 3PGpjs did not consider the volume lost due to mortality or thinning, but this is typically part of the MAI calculated for forestry purposes. So r3PG (and 3-PGmix) calculates MAI including the volume that was lost due to mortality or thinning.

**Comment by Theo025** [comment]
@trotsiuk you are not wrong. 

@DavidForrester thank you for making it clearer. I will play around these parameters and let you know what i get.

**Comment by Theo025** [comment]
This is an interesting point i have to pay attention to in my research.

@DavidForrester @trotsiuk Thank you!
