### ISSUE TITLE
cohort age tends not to be the trees' true age

### ISSUE THREAD

**Issue by twest820** [trotsiuk/r3PG#53]
As of r3PG 0.1.3, with the workaround for #52, what I get in the output is the start month of simulation is age 0. This is equivalent to assuming simulation starts at germination, which is awkward for silviculture based on nursery stock such as plug+0 or 2+0. I didn't see a way of addressing this in #42 or #49.

The workaround I'm using for now is to maintain distinct r3PGage and trueAge columns in the tibbles. This isn't a big deal as we don't have complex, multi-cohort stands and therefore don't have too many planting age offsets to keep track of. But it'd be easier if r3PG could emit fully accurate tree ages. An alternate workaround is to start the simulation in the greenhouse and then carry it through any container to bare root transitions before planting at the harvest unit. However, it's a much simpler setup if weather inputs are needed only for the management unit the trees end up on and you don't need to insert "thinning" treatments to represent exogenous planting mortality.

A second motivation for such age bookkeeping is correctly selecting the simulation months matching field measurements in order to calculate model error. Some measurement datasets define age 0 as the planting age and therefore compose naturally with r3PG's current implementation. Most of the ones I work with don't, though, and translating the dataset to r3PG's age origin tends to be more complex than maintaining two age columns.

It's also common in the monitoring plot datasets I work with that planting records are minimal or absent and measurements don't start until trees have reached some requirement such as a 2 cm or 5 cm DBH. In such cases there may not be data to initialize a simulation cohort until the trees are 5-12+ years old, resulting a greater disparity between true ages and 3-PG ages. On production units the first inventory might not be until somewhere in the range of age 20-35, which in some species is enough it's probably a good idea to start manipulating the MaxAge, nAge, and rAge species parameters to account for discrepancies between 3-PG's ages and the trees' actual ages. This too seems like avoidable complexity. Iterating sims to figure out when to introduce a naturally recruited cohort so that running forward matches its measurements is, in principle, probably preferred in respect to fully capturing stand state into a model. However, such an approach isn't always feasible or practical.

I think the cleanest way to simplify these cases might be to have `d_species$germinated` as well as `d_species$planted`, calculating age from `germinated` but continuing to use planted as the trigger for the management action. That makes it easy to specify a plausible spring germination month, for example, and lets the code deal with sorting out the timing details of things like fall versus winter plantings rather than making users recalculate an offset. If `germinated` defaults to `planted` it's a non-breaking change and transparent to existing code.

**Comment by trotsiuk** [comment]
@DavidForrester would you have some comment on `true age`. I thought we have implemented it in the same way in the the `3pg-mix`.

**Comment by DavidForrester** [comment]
Thanks for the questions. It is a fair point that “planted” date could probably be more accurately called germination date. The age provided by 3-PG will be the time since germination assuming the germination date is entered as the “planted” date. As far as I know, this is how it is usually be used. If the plants actually start in a nursery before being planted in the field, then the simulation can begin at the time they are planted in the field as defined by “from” (with the input “planted” as the germination date). The stand structure at the time when the seedlings are moved to the field, as defined by “from”, would need to be provided (stems_n, biom_stem, biom_root, biom_foliage) based on measurements of seedling weights. One of the original aims when creating 3-PG was to keep it as simple as possible, so adding another variable such as “germinated” as an input would need to be very carefully considered. 3-PG is not as accurate for very young ages (e.g. a few months or tree diameters < 4 cm or so) so this may not improve the accuracy.

Regarding the use of MaxAge, nAge, and rAge to control the outputs. This is not recommended unless the stands are actually approaching their maximum ages (much later than their peak in current annual increment or leaf area index) because this is when this age-related decline process is important. If productivity is too high at intermediate ages, then there is probably something else that needs to be corrected. For example, for many tree species and sites, an age of 20-35 years is still earlier than the peak current annual increment (examples of exceptions include fast growing plantation species), but this is much younger than the age-related decline based on MaxAge, nAge, and rAge should occur. Without manipulating MaxAge, nAge, and rAge there will still be a decline in growth after the peak in current annual increment because of other patterns in 3-PG that are influenced by age (e.g. SLA) or size (e.g. partitioning).
