### ISSUE TITLE
volume_cum / cumulative Volume

### ISSUE THREAD

**Issue by Rasilgon** [trotsiuk/r3PG#63]
Hi, 

I’m running the r3PG (v0.1.4) without thinning for mix stands using the parameters from Forrester et al. 2021 and the specified settings,  and I am a bit confused with the variable cumulative volume / volume_cum.

In some model runs, there is decreasing volume_cum (CumulativeVol). The volume (StandVol) shows the same pattern.  I would expect cumulative volumes to either increase or not increasing at all, if all trees of cohort/species have been removed, but not to decrease.  

Based on the manual (CumulativeVol as StandVol + ExtractedVol + any volume lost due to mortality) and on the behaviour of the variables volume and volume_cum, it would seem that CumulativeVol is the total or *cumulative* volume at instant t, not since the start of the simulation, as I initially assumed it to be. Is this correct?  

Thanks!

**Comment by trotsiuk** [comment]
HI @Rasilgon,

I would agree that the cumulative volume shall increase. In the vignette example everything works well. Can you please provide the example where you face this issue.


```
library(r3PG)
library(dplyr)
library(ggplot2)

out_3PG <- run_3PG(
  site        = d_site, 
  species     = d_species, 
  climate     = d_climate, 
  thinning    = d_thinning,
  parameters  = d_parameters, 
  size_dist   = d_sizeDist,
  settings    = list(light_model = 2, transp_model = 2, phys_model = 2, 
                     height_model = 1, correct_bias = 0, calculate_d13c = 0),
  check_input = TRUE, df_out = TRUE)

i_var <- c('stems_n',  'volume', 'volume_cum')
i_lab <- c('Stem density', 'volume', 'volume_cum')

out_3PG %>%
  filter(variable %in% i_var) %>%
  mutate(variable = factor(variable, levels = i_var)) %>%
  ggplot( aes(date, value))+
  geom_line( aes(color = species), size = 0.5)+
  facet_wrap( ~ variable, scales = 'free_y', ncol = 3, 
              labeller = labeller(variable = setNames(i_lab, i_var) )) +
  scale_color_brewer('', palette = 'Dark2') +
  theme_classic()+
  theme(legend.position="bottom")+
  xlab("Calendar date") + ylab('Value')
```

![image](https://user-images.githubusercontent.com/15097779/142375827-b55ed8ad-5f11-4c19-a7dd-d1763cc1dba4.png)

**Comment by Rasilgon** [comment]
Thanks for the quick reply! 
The data is here https://drive.google.com/file/d/1BPuO0f_pG0wdYARBVgmIdc-9H4fAU7Id/view?usp=sharing. Initial tree densities might be too high, but I assume this should not affect the behaviour of volume_cum.
 And I can run your code with the data:


> library(r3PG)
> library(dplyr)
> library(ggplot2)
> 
> load("testData.RData")
> 
> out_3PG <- run_3PG(
>   site        = mySite, 
>   species     = mySpecies, 
>   climate     = climate[[2]], 
>   parameters  = myParameter, 
>   size_dist   = mySizeDist,
>   settings    = list(light_model = 2, transp_model = 2, phys_model = 2,
>                     height_model = 2, correct_bias = 1, calculate_d13c = 0),
>   check_input = TRUE, df_out = TRUE)
> 
> i_var <- c('stems_n',  'volume', 'volume_cum')
> i_lab <- c('Stem density', 'volume', 'volume_cum')
> 
> out_3PG %>%
>   filter(variable %in% i_var) %>%
>   mutate(variable = factor(variable, levels = i_var)) %>%
>   ggplot( aes(date, value))+
>   geom_line( aes(color = species), size = 0.5)+
>   facet_wrap( ~ variable, scales = 'free_y', ncol = 3, 
>               labeller = labeller(variable = setNames(i_lab, i_var) )) +
>   scale_color_brewer('', palette = 'Dark2') +
>   theme_classic()+
>   theme(legend.position="bottom")+
>   xlab("Calendar date") + ylab('Value')


![image](https://user-images.githubusercontent.com/10464055/142380860-64f50fcb-cd2c-409d-9238-9fc7fafb0e90.png)

**Comment by trotsiuk** [comment]
I think there are couple of things:

- indeed the calculation of `volume_cum` was based on `volume_change`. And since the volume was decreasing, the cumulative volume also decreased. Now adjusted that the cumulative volume can't decrease.
- however, as the volume is decreasing I thin the parameters (particularly height) are not correctly set. While using the default parameters one can expect sometimes unrealistic values. To see that, you can also play with settings and change e.g. height model or bias correction

Please let me know if the issue  resolved, and close it if yes.

**Comment by Rasilgon** [comment]
Thanks for the fix and the hint!

I ran the same code with the same data and now `volume_cum` does not decrease. Now it remains constant. See below the outputs, this time also plots  for height, dbh and biomass.

![image](https://user-images.githubusercontent.com/10464055/142431275-e7ac4b51-4fb7-459b-af0c-6d9de27c37be.png)


Concerning the parameters, I did not use the package default, but the one from the calibration for Switzerland (Forrester et al. 2021).

**Comment by trotsiuk** [comment]
Yes, that is correct. As you see the `volume` is decreasing (I believe this is because the biomass is decreasing, which is the result of other calculations). The `volume_cum` is remaining constant, as it shall not decrease as you mentioned at the beginning. 

Regarding the data. I wonder if the numbers are not too low for the initial biomass in your data. E.g. 
```
  species          planted fertility stems_n biom_stem biom_root biom_foliage
  <chr>            <chr>       <dbl>   <dbl>     <dbl>     <dbl>        <dbl>
1 Fagus sylvatica  1999-04         1    2500   0.0833     0.126       0.0286 
2 Quercus petraea  1999-04         1    1000   0.00624    0.0146      0.00312
3 Pinus sylvestris 1999-04         1    1000   0.0212     0.0153      0.0218 
```

You start the simulation at 2021, and your trees with the age 20 would have only `0.0833 /0.00624/0.0212 ` in stem biomass. For me those are extremely low number. The `species` table shall contain the biomass/density of the trees at the start of the simulation, not at the planting age (until the planting age is also the start fo the simulation). As a result at age 20 you have trees with size only 1 cm and volume almost 0. Please cross check whether you are putting the biomass numbers at the start of the simulation or at planting?

Secondly, I think the issue with the biomass is related to the interaction of the trees height, entering the same layer. Consequently, Oak have higher competition, and less NPP to get. Since it is a broadleaf it can't compensate for the leaves loss in spring, and can rebuilt the biomass.

Maybe @DavidForrester would have additional suggestion.

![image](https://user-images.githubusercontent.com/15097779/142585967-c5d1e449-be68-45aa-bd60-7e301afb835b.png)

**Comment by Rasilgon** [comment]
HI @trotsiuk,

yes, you are right about the age. It is a mistake, trees should be 2 years old, not 20.  The planting date is 2019-04, not 1999-04. I've fixed in the testData file.

Your explanation about biomass, height and foliage loss sounds sensible. Probably the behaviour of the model here is too extreme because fertility is set to maximum (1) for the tree species.  With lower fertility (0.5 for all), competition is not that intense, and the behaviour, therefore, not that extreme, but  the patter holds. Pine entering top layer relates to  volume and NPP decrease of oak. 

Thanks for explanation! The model and package are great to explore interactions among species!



![image](https://user-images.githubusercontent.com/10464055/142597801-926a0b23-fe10-4dd5-831d-6bfd15465e4e.png)

**Comment by Rasilgon** [comment]
Hi,

to bring more clarity here, I found that there was a conversion unit error in the temperature time series from 2051 onwards (I updated the testData). This might be behind the abrupt decline of oak. See below the same plot of @trotsiuk (fertility = 1 all spp) with the corrected climate data. Anyway, the explanation about the decline still holds, although now the decline is not so dramatic.
Sorry for the confusion, I assumed that the climate data was correct. I should have checked first. 


![image](https://user-images.githubusercontent.com/10464055/142614355-22d7ca4d-f4e8-42ae-918b-6c8158f86942.png)
