### ISSUE TITLE
Check - prepare_site prepare_species

### ISSUE THREAD

**Issue by Rasilgon** [trotsiuk/r3PG#73]
I think that it would be good to include  checks or functions, *prepare_site*  and *prepare_species* , to ensure that:

- soil class is 0, 1, 2, 3 or 4
- fertility is within 0 and 1

Currently, one can run the model with any possible value for these parameters. Besides, prepare_input gives the erroneous feeling that such check is done.

**Comment by twest820** [comment]
Broadly agree. Routine parameter validation is, in general, missing. In both R and on the Fortran side. I feel many more checks would be appropriate to catch obviously wrong site, species, and (beyond the scope of this issue as currently described) size distribution parameters (which is why they're implemented in my branch). (There's also cases, such as #68, where the Fortran will misbehave for valid input and the lack of debug assertions likely means some issues are going undetected during development.)

Be aware, however, that `soil_class` is real valued parameter and nonpositive values work as switches. The manuals and `md_3PG.f95` are mismatched on this. It's unclear to me if four is an upper bound for `soil_class` or if higher values are valid, though going above more than 5.5-8 looks numerically dubious.
```
        ! Assign the SWconst and SWpower parameters for this soil class
        if ( soil_class > 0.d0 ) then
            ! Standard soil type
            SWconst(:) = 0.8d0 - 0.10d0 * soil_class
            SWpower(:) = 11.d0 - 2.d0 * soil_class
        elseIf ( soil_class < 0.d0 ) then
            ! Use supplied parameters
            SWconst(:) = SWconst0(:)
            SWpower(:) = SWpower0(:)
        else
            ! No soil-water effects
            SWconst(:) = 999
            SWpower(:) = SWpower0(:)
        end if
```
