### ISSUE TITLE
Soil class - Soil texture

### ISSUE THREAD

**Issue by Rasilgon** [trotsiuk/r3PG#77]
Hi all! 

I am trying to derive the soil classes for `r3PG ` using the ESDB.  In the DB there are layers for silt, clay and sand content of the soil. These could be used to obtain soils texture classes, which is what the soil class in the model represents, as I understood so far. However, I could not find the definition of soil classes of 3PG, nor a reference to which system it is based on, e.g., USDA.  Besides, the soil classes of 3PG do not cover all texture classes,  for example loam or silty loam.

Additionally, I wonder that if the purpose of providing a soil class is to modify `SWconst ` and  `SWpower ` linearly, then the relationship could be explicit, like `SWconst ` and  `SWpower ` are inversely proportional to clay content, and soil class could be continuos instead of discrete. 

In any case, it would be great to have some clear criteria/guidance about how to classify a given soil based on its texture, so that it makes sense to 3PG.  :)

**Comment by Rasilgon** [comment]
Thanks @twest820  for the hint!  I had a look at them :)

Denmead and Shaw  worked with just one soil type  (silty clay loam) and provide results to justify the shape of the curve itself, not how it's affected by clay content,  nor how it varies depending on texture. I could not access a full version Dunin et al. 1985, but it'd seem to also be very specific soil-wise, and only provide results for the curves shape.  I mean the curves from [Landsberg and Waring 1997](https://doi.org/10.1016/S0378-1127(97)00026-1)', Relationship between the soil water modifier and the moisture ratio.  

[Williams et al. 1983](https://www.publish.csiro.au/sr/sr9830015), also cited in [Landsberg and Waring 1997](https://doi.org/10.1016/S0378-1127(97)00026-1)', would rather seem the source of the 3PG soil classes.  From what I understood, they worked with sand and different soils with significant amount of clay, which could be translated in the 3PG classes: sand, sandy loam, clay loam, and clay. 

I wonder whether a detailed texture classification is possible regarding the hydraulic properties of each class. The USDA systems has probably too many classes. Perhaps broader soil textural classes as the ones used in [HYPRES](https://www.sciencedirect.com/science/article/pii/S0016706198001323?casa_token=fxz-6bHjg3QAAAAA:vBs8aNUE0bvmBxcl6dpFP3Ewxv9NYduiGFFyrTgLM8ZuvRC4qi2QiPHFUNDKJYeEBchx_kzWZEYo), which are also the ones in the [ESDB](https://esdac.jrc.ec.europa.eu/resource-type/european-soil-database-soil-properties), are a better option. However, without evidence, we can only assume. Since the soil class in the model is actually not categorical, and not even has to be an integer, it can be easily tweaked.  We could cover the range from HYPRES, coarse (sand) to very fine (clay), with values ranging from 1 and to 4 or 5. If the evidence and reasoning of 3PG classes is sound,  we could assume this alternative approach to be a valid temporary patch.

![image](https://user-images.githubusercontent.com/10464055/161043258-eaadfb7c-02ad-40ed-a1b6-8fb7537b2116.png)

Your approach of  defining  `SWconst `and `SWpower` sounds good as well, but it requires more expert knowledge from the user. In this sense, soil texture class is very straightforward.

**Comment by florianhartig** [comment]
Hir Ramier, @JohannesOberpriller had some kind of pipeline to derive soil inputs from, not sure if he also used ESDB but may well be!

**Comment by twest820** [comment]
A few follow on thoughts here:

- It looks like the most recent version of the European Soil Database is 2.0, which is from 2001. I'm not up on European soil work (not my continent) but that probably means the ESDB is, at least nominally, superseded by the 250 m resolution [SoilGrids 2.0](https://soilgrids.org/) which covers most of six continents. If ESDB is similar to the older raster datasets I've worked with elsewhere, SoilGrids may also offer advantages in harmonization of different surveys, depth standardization, and consistent availability of sand, silt, clay, and coarse fragment fractions.
- In the areas I work in SoilGrids is a fallback data product as other work provides AI-based estimates of texture components along with Mualem-van Genuchten and Brooks-Corey soil water retention curve parameters' probability distributions at 30 m resolution. This permits estimation of plant available water's probability distribution from the retention curves rather than needing to apply one's own pedotransfer functions or go through tools such as Rosetta3, which is also AI based but (as of when I last checked the package) doesn't surface its internal probability distributions to R. I find 30 m resolution is also helpful giving some quantification of the within stand variability neglected by 3-PG. 
- Not all 3-PG variants obtain fθ from `SWconst` and `SWpower`. iLand, in particular, uses some regressions to estimate Campbell soil water retention curve parameters from soil texture and then calculates fθ from the water curve's matric potential. One thing I've found convenient about this approach is you can swap the water curve for one with soil dataset parameters without changing how fθ works. I lack visibility into what the thinking is for updating 3-PGmix or pjs to integrate with more recent soil datasets but perhaps this might be an option to consider.
- The biggest uncertainties I have are around integrating soil layers across rooting depth to get plant available water and set the site's max and min soil water content. Part of that is lack of information on where soil depth or pans impose limits on rooting depth and part of that is the interactions between root network sizes and hydraulic redistribution. For the planted stands 3-PGmix and pjs 2.7 tend to be applied to water available to seedlings likely depends on seedling size and retention levels among larger trees. Since a single layer, time-invariant soil model can't capture those effects some caution is probably wise when trying to predict planting or advance regeneration success.

The only location I got a soil texture hit on when keyword searching [Johannes' thesis](https://epub.uni-regensburg.de/52405/) cites an older 0.5 degree soil dataset ([Batjes 2005](https://data.isric.org/geonetwork/srv/api/records/d9eca770-29a4-4d95-bf93-f32e1ab419c3)).
