### ISSUE TITLE
Calibration in the vignette does not work

### ISSUE THREAD

**Issue by florianhartig** [trotsiuk/r3PG#89]
Hi Vova,

@LisaHuelsmann alerted me to the fact that the current calibration code in the vignette does not result in a good calibration, for whatever reason. In the vignette, we currently load MCMC results from a previous calibration. With this data, the results are fine 

When re-running everything, we get results such as this one 

<img width="555" alt="image" src="https://github.com/trotsiuk/r3PG/assets/5457753/3c598dbd-7009-4ea2-8a9a-70a72e1da880">

I haven't explored in detail, but given that the sampler is unlikely to fail, and that the plots work perfectly when loading the old MCMC runs, I assume the issue must be somewhere in the likelihood, or else there was a change in the data or something like that?

These are the estimated parameters when re-running the MCMC 

<img width="455" alt="image" src="https://github.com/trotsiuk/r3PG/assets/5457753/61caec55-6e90-4cf2-a921-da68e1540a01">

These are the old parameters

<img width="458" alt="image" src="https://github.com/trotsiuk/r3PG/assets/5457753/50a06950-d943-4631-a9c7-3c8856fa87b3">

The most obvious difference are in the root and foliage errors, where we seem to have a massively larger misfit compared to the old runs. Doe that ring any bells, i.e. did you change something related to this in the code or in the data?

Some other comments that I had when skimming the vignette

- Mixing is very bad, could maybe be improved by sampler settings but absent of that I would set thin = 10 or so to save disk space
- Likelihoods / Bayesian setup is partly redundant (specified several times)

If you wanted to, once I have time, I could maybe go over the vignette and try to improve / extend a bit the calibration code? In any case, however, we should find the problem first. 

Cheers,
Florian

**Comment by LisaHuelsmann** [comment]
Thanks for starting the discussion @florianhartig. 

I have started searching for a solution, but I didn't find anything strange so far. Not in the output formats (i.e. data.frame versus array) and not in the way the likelihood is written. Maybe the search is easier for you @trotsiuk. If I can still help with something, let me know.

btw: thanks for putting this together. I used the R implementation of 3PG for a course on dynamic models and the vignette is a good starting point for the project the students are working on in the second week.

**Comment by trotsiuk** [comment]
Hi @florianhartig and @LisaHuelsmann 

Thanks for spotting this issue. There are actually couple of things combined, which have caused this issue.

### Issue

- There was an old issue in the likelihood function, which took the default values for error instead of the range #54 . While during the commit I have adjusted the likelihood function and uploaded the new data for Morriss sensitivity, I have not uploaded the new data for the mcmc (see here the commit https://github.com/trotsiuk/r3PG/commit/c5da7bc64eb1ca48c7bd31582983c1b182290b38)

- Due to the further development of the package (particularly changing the default values of the model https://github.com/trotsiuk/r3PG/commit/1efd011cb0d29a521ee7a50dbe85e2cd7118fa3a) the likelihood function was incorect (the default values which are not calibrated were taken for a different species). This caused larger discrepancy of the model. Therefore, the likelihood function in the vignette shall be corrected from:
```
  par_df = data.frame(parameter = par_cal_names[-err_id], piab = par_v[-err_id])
```
to 

```
  par_df = dplyr::bind_rows(dplyr::filter(par_def.df, !parameter %in% par_cal_names),
                            data.frame(parameter = par_cal_names[-err_id], piab = par_v[-err_id]))
```


### Test

I have only run the MCMC for `4e+04`, however it seems to be much more reasonable.
```
# MCMC sampler:  DEzs 
# Nr. Chains:  9 
# Iterations per chain:  13334 
# Rejection rate:  0.966 
# Effective sample size:  141 
# Runtime:  1663.992  sec. 
 
# Parameters
                    psf     MAP    2.5%  median   97.5%
pFS20             2.383   0.155   0.094   0.140   0.383
aWS               1.307   0.179   0.089   0.153   0.265
nWS               1.308   2.142   2.054   2.186   2.369
pRn               2.828   0.389   0.078   0.229   0.389
Tmin              8.313  -8.446  -9.915  -7.647   1.501
Topt              1.686  29.583  13.114  27.044  29.880
Tmax              2.594  35.144  28.259  34.253  38.903
fN0               3.510   0.973   0.146   0.353   0.993
fNn               3.587   1.638   0.303   1.357   1.781
MaxAge            1.758 279.190 238.112 276.452 334.091
rAge              2.544   0.228   0.194   0.266   0.471
gammaN1           1.959   0.869   0.017   0.856   2.981
thinPower         1.771   1.892   1.204   1.739   2.063
mS                2.417   0.075   0.025   0.089   0.318
alphaCx           1.834   0.041   0.021   0.046   0.066
rhoMin            4.590   0.378   0.374   0.610   0.698
rhoMax            1.423   0.536   0.273   0.558   0.735
aH                3.040   1.997   1.771   3.266   5.838
nHB               4.328   0.326   0.019   0.252   0.579
nHC               3.579   0.469   0.028   0.401   0.695
err_basal_area   26.491  13.771   0.662   1.833  14.837
err_dbh           5.971   0.231   0.210   6.788  10.475
err_height        1.280   0.863   0.796   2.027   7.457
err_biom_stem    11.597  25.578   1.897   3.692  25.426
err_biom_root     5.788   1.118   1.187   9.071  14.501
err_biom_foliage  1.317   0.265   0.182   0.314   7.831
```
![image](https://github.com/trotsiuk/r3PG/assets/15097779/75ec5e09-120a-46a2-beb2-afbab66acd13)


### Correction

In the next days I will try to re-run the full simulation and re-upload all the data and vignette.

**Comment by LisaHuelsmann** [comment]
Thanks for checking, @trotsiuk, and great you already found a solution!

More generally, I felt it is a bit errorprone if the functions rely on objects that need to be defined in the global environment. Now this is not only the case for _par_cal_names_ and _observ_solling_mat_ but also for _par_def.df_. If you will work on this @florianhartig this may be also a thing to improve.

**Comment by florianhartig** [comment]
Hi Vova,

thanks, great that we found the problem. Before you commit, do you want to have me to have a quick look at the code? I would maybe to a few comments about setting and also would suggest

- try to improve mixing if possible
- use thin = 10 or so to reduce the size of the MCMC sample (which is currently unreasonably large given the autocorrelation)
- add a plot to diagnose burn-in and remove burn-in for inference (for pedagogical reasons) 

Cheers
F

p.s.: it's a good thing that we linked in the paper directly in the vignette so that we can fix those errors. I wonder: should we add a note in the beginning (or better the end) of the vignette about things that have changed from the published version?

**Comment by trotsiuk** [comment]
Hi both,

### Vignette update

I have now made the main correction of the vignette in the new [branch](https://github.com/trotsiuk/r3PG/tree/%2389_vignette_update). Since Florian want to make some suggestions, I have not yet re-run the MCMC. This will be done in the end and saved to the vignette_data.

If you feel like, you can work on the branch, particularly on the [`r3PG-ReferenceManual.Rmd`](https://github.com/trotsiuk/r3PG/blob/%2389_vignette_update/vignettes_build/r3PG-ReferenceManual.Rmd).

### Global variables

@LisaHuelsmann indeed, it would be beneficial to avoid it and use them as parameters for the function. However, when running the MCMC it is not possible to specify the parameters of the LL function (@florianhartig correct me if I'm wrong). E.g. in this set-up 
```
morris_setup <- createBayesianSetup(
  likelihood = r3pg_ll, 
  prior = createUniformPrior(par_cal_min, par_cal_max, par_cal_best), 
  names = par_cal_names)
```
it is not possible to write something like this to my knowledge
```
morris_setup <- createBayesianSetup(
  likelihood = r3pg_ll(.x, par_names = names_v, par_default = def_v, ...), 
  prior = createUniformPrior(par_cal_min, par_cal_max, par_cal_best), 
  names = par_cal_names)
```
This means, that we would need then to define two separate LL function for Moriss and MCMC, as they are taking different input parameters (Morriss testing all variables and for MCMC we subset only 20). However, as said I might be wrong.

### News and information

The changes will be definitely added to the `NEWS` but maybe it is also good idea to mention it in the vignette. Or put a note, that _vignette has been updated since first publication, please refer to the `NEWS` for more information_

**Comment by florianhartig** [comment]
Hi @trotsiuk, just realised that I don't have push access to the repo - can you add me as a collaborator? Will be easier if I can work in the branch directly.

**Comment by florianhartig** [comment]
@trotsiuk, sorry, my bad, I think I do have push access, all good. F

**Comment by trotsiuk** [comment]
Thanks @florianhartig for the corrections. I have now re-run the mcmc and the output looks good. However the psrf is still 1.237. Not sure whether there is a need to re-run it for longer time to get under 1.2

**Comment by florianhartig** [comment]
I wanted to try this out but then didnt have time any more

**Comment by florianhartig** [comment]
I would add this to the vignette though because it shows the recommended workflow. In the end, more people than one does think just copy the vignette.

**Comment by florianhartig** [comment]
not much more detailed, I would just want to avoid to set a bad example - in any case, as I haven't re-run the MCMCs yet, could you run a trace-plot and see how fast it runs into equilibrium, set the burnin value (use start = XXX) based on this, and look again at the psrf?

**Comment by trotsiuk** [comment]
Florian, I have re-run the MCMC. The chains converged. Here are the actual MCMC runs ([data](https://github.com/trotsiuk/r3PG/tree/%2389_vignette_update/vignettes_build/vignette_data)). The vignette and data are updated. I would be happy to merge it and update on the CRAN. 

Please have a look whether you have some comments.

**Comment by florianhartig** [comment]
Hi @trotsiuk,

sorry for the slow reply - I've been swamped with teaching and faculty meetings in the last days / weeks. 

I have made a few more changes in the vignette branch - have a look if that's fine for you, from my side the vignette is good to go!

Cheers
Florian

**Comment by florianhartig** [comment]
p.s.: I'm not showing the results of the summary() function in the vignette because of the large correlation matrix. 

With this example, I noted that it's suboptimal that this is automatically calculated by summary() even if there are a large number of parameters. I will change this in BayesianTools, once this is changed it would make sense to show the summary() results as well.

Cheers
F

**Comment by trotsiuk** [comment]
Thanks for the work @florianhartig . I have now incorporated changes and merged to the main branch. I will do some small adjustments (mainly checks and warnings) in the next days and will submit it to CRAN.

Regarding the `summary` function I fully agree. I think it would be useful to have summary without all the matrix (or chose whether you want matrix or summary).

**Comment by LisaHuelsmann** [comment]
Thanks a lot @trotsiuk!
I just had a brief look and I was wondering if there is one zero missing in the start argument when drawing the parameters (i.e. start = 10000 vs 100000)?

**Comment by trotsiuk** [comment]
yes, good point
